import { create } from "zustand";
import { persist, createJSONStorage } from "zustand/middleware";
import AsyncStorage from "@react-native-async-storage/async-storage";

export type Language = "el" | "en";

// Translations - Greek in ALL CAPS without accents per spec
export const translations = {
  el: {
    // Browse
    browse_title: "ΑΓΟΡΑ",
    browse_subtitle: "Ανακαλυψε συσκευες κοντα σου",
    search_placeholder: "Αναζητηση...",
    all_categories: "ΟΛΑ",
    phones: "ΚΙΝΗΤΑ",
    tablets: "TABLETS",
    laptops: "LAPTOPS",
    accessories: "ΑΞΕΣΟΥΑΡ",
    verified_only: "ΜΟΝΟ ΠΙΣΤΟΠΟΙΗΜΕΝΑ",
    no_listings: "ΔΕΝ ΒΡΕΘΗΚΑΝ ΑΓΓΕΛΙΕΣ",
    results_singular: "αποτελεσμα",
    results_plural: "αποτελεσματα",
    try_different_filters: "Δοκιμασε διαφορετικα φιλτρα η αναζητηση",
    // Conditions (UPPERCASE = no accents)
    condition_new: "ΚΑΙΝΟΥΡΓΙΟ",
    condition_like_new: "ΣΑΝ ΚΑΙΝΟΥΡΓΙΟ",
    condition_good: "ΚΑΛΟ",
    condition_fair: "ΜΕΤΡΙΟ",
    condition_parts: "ΑΝΤΑΛΛΑΚΤΙΚΑ",
    // Condition descriptions (lowercase = with accents)
    condition_new_desc: "Αχρησιμοποιητο, στην αρχικη συσκευασια",
    condition_like_new_desc: "Ελαχιστη χρηση, αριστη κατασταση",
    condition_good_desc: "Μικρα σημαδια χρησης",
    condition_fair_desc: "Φανερη χρηση, πληρως λειτουργικο",
    condition_parts_desc: "Για ανταλλακτικα μονο",
    // Sell
    sell_title: "ΝΕΑ ΑΓΓΕΛΙΑ",
    sell_subtitle: "Πουλησε τη συσκευη σου στο Mobile Unit",
    photos_label: "ΦΩΤΟΓΡΑΦΙΕΣ (3-10)",
    min_photos: "Ελαχιστο 3 φωτογραφιες",
    title_label: "ΤΙΤΛΟΣ",
    category_label: "ΚΑΤΗΓΟΡΙΑ",
    condition_label: "ΚΑΤΑΣΤΑΣΗ",
    city_label: "ΠΟΛΗ",
    price_label: "ΤΙΜΗ",
    brand_label: "ΜΑΡΚΑ",
    model_label: "ΜΟΝΤΕΛΟ",
    location_label: "ΤΟΠΟΘΕΣΙΑ",
    description_label: "ΠΕΡΙΓΡΑΦΗ",
    publish_button: "ΔΗΜΟΣΙΕΥΣΗ ΑΓΓΕΛΙΑΣ",
    creating: "ΔΗΜΙΟΥΡΓΙΑ...",
    pricing_guide: "ΟΔΗΓΟΣ ΤΙΜΟΛΟΓΗΣΗΣ",
    vat_free: "Χωρις ΦΠΑ για μεταχειρισμενα",
    check_pricing: "Δες Τιμες Αγορας Pandas",
    // Profile
    profile_title: "ΠΡΟΦΙΛ",
    my_listings: "ΟΙ ΑΓΓΕΛΙΕΣ ΜΟΥ",
    listings_count: "ΑΓΓΕΛΙΕΣ",
    views_count: "ΠΡΟΒΟΛΕΣ",
    create_new: "ΔΗΜΙΟΥΡΓΗΣΕ ΝΕΑ ΑΓΓΕΛΙΑ",
    no_listings_yet: "Δεν εχεις ακομα αγγελιες",
    create_first: "Δημιουργησε την πρωτη σου",
    settings: "ΡΥΘΜΙΣΕΙΣ",
    support: "ΥΠΟΣΤΗΡΙΞΗ",
    legal: "ΝΟΜΙΚΑ",
    sign_out: "ΑΠΟΣΥΝΔΕΣΗ",
    sign_in: "ΣΥΝΔΕΣΗ",
    sign_in_to_profile: "Συνδεσου στο προφιλ σου",
    manage_listings_desc: "Διαχειρισου τις αγγελιες και τις ρυθμισεις του λογαριασμου σου",
    user_fallback: "Χρηστης",
    language_label: "ΓΛΩΣΣΑ",
    // Service
    service_title: "ΥΠΗΡΕΣΙΕΣ",
    grading_cta: "ΒΑΘΜΟΛΟΓΗΣΗ ΣΤΟ IREPAIR",
    book_appointment: "ΚΛΕΙΣΕ ΡΑΝΤΕΒΟΥ",
    diagnostic_fee: "ΔΙΑΓΝΩΣΤΙΚΟ ΤΕΛΟΣ",
    refunded_on_purchase: "Επιστρεφεται αν αγορασετε",
    // Common
    loading: "ΦΟΡΤΩΣΗ...",
    error: "ΣΦΑΛΜΑ",
    success: "ΕΠΙΤΥΧΙΑ",
    cancel: "ΑΚΥΡΩΣΗ",
    confirm: "ΕΠΙΒΕΒΑΙΩΣΗ",
    rhodes: "ΡΟΔΟΣ",
    add: "ΠΡΟΣΘΗΚΗ",
    remove: "ΑΦΑΙΡΕΣΗ",
    // Onboarding
    welcome_title: "Καλως ηρθες στο Mobile Unit",
    welcome_subtitle: "Επιλεγμενες αγγελιες. Ασφαλης παραλαβη. Τοπικα.",
    get_started: "Ξεκινα",
    have_account: "Εχω ηδη λογαριασμο",
    skip: "Παραλειψη",
    next: "Επομενο",
    // Value props
    value_approved_title: "Εγκεκριμενες Αγγελιες",
    value_approved_desc: "Καθε αγγελια ελεγχεται απο την ομαδα μας",
    value_pickup_title: "Ασφαλης Παραλαβη",
    value_pickup_desc: "Συναντησεις σε επιλεγμενα σημεια",
    value_inspection_title: "Ελεγχος & Βαθμολογηση",
    value_inspection_desc: "Προαιρετικος ελεγχος απο τεχνικους",
    // City Gate
    select_city: "Επελεξε Πολη",
    select_city_subtitle: "Για να δεις αγγελιες κοντα σου",
    available_now: "Διαθεσιμο τωρα",
    coming_soon: "Συντομα",
    other_city: "Αλλη πολη / Εξωτερικο",
    use_location: "Χρηση τοποθεσιας μου",
    // Waitlist
    join_waitlist: "Μπες στη λιστα αναμονης",
    waitlist_title: "Λιστα Αναμονης",
    waitlist_subtitle: "Θα σε ειδοποιησουμε οταν ειμαστε διαθεσιμοι στην περιοχη σου",
    email_label: "EMAIL",
    interest_label: "ΕΝΔΙΑΦΕΡΟΝ",
    buyer: "Αγοραστης",
    seller: "Πωλητης",
    both: "Και τα δυο",
    phone_label: "ΤΗΛΕΦΩΝΟ (προαιρετικο)",
    social_label: "INSTAGRAM/SOCIAL (προαιρετικο)",
    notes_label: "ΣΗΜΕΙΩΣΕΙΣ (προαιρετικο)",
    referral_code_label: "ΚΩΔΙΚΟΣ ΠΡΟΣΚΛΗΣΗΣ (προαιρετικο)",
    consent_label: "Συμφωνω να λαμβανω ειδοποιησεις",
    submit_waitlist: "Εγγραφη",
    // Waitlist Success
    waitlist_success_title: "Εισαι στη λιστα!",
    waitlist_success_subtitle: "Θα σε ειδοποιησουμε οταν ανοιξουμε στην περιοχη σου",
    your_referral_code: "Ο κωδικος προσκλησης σου",
    share_referral: "Μοιρασου και ανεβα στη λιστα",
    share_button: "Κοινοποιηση",
    copy_link: "Αντιγραφη link",
    copied: "Αντιγραφηκε!",
    view_demo: "Δες Demo",
    referral_bonus: "+3 θεσεις για καθε φιλο",
    // Demo Mode
    demo_banner: "Demo Mode",
    demo_locked_title: "Διαθεσιμο μονο στη Ροδο",
    demo_locked_subtitle: "Προς το παρον ειμαστε διαθεσιμοι μονο στη Ροδο",
    demo_locked_cta: "Μπες στη λιστα αναμονης",
    // Cities
    city_rhodes: "Ροδος",
    city_athens: "Αθηνα",
    city_thessaloniki: "Θεσσαλονικη",
    city_patras: "Πατρα",
    city_heraklion: "Ηρακλειο",
    city_larissa: "Λαρισα",
    city_volos: "Βολος",
    city_ioannina: "Ιωαννινα",
    city_chania: "Χανια",
    city_london: "London",
    city_berlin: "Berlin",
    city_paris: "Paris",
    city_amsterdam: "Amsterdam",
    city_rome: "Rome",
    city_madrid: "Madrid",
    // Countries
    country_greece: "Ελλαδα",
    country_uk: "United Kingdom",
    country_germany: "Germany",
    country_france: "France",
    country_netherlands: "Netherlands",
    country_italy: "Italy",
    country_spain: "Spain",
    country_other: "Αλλη χωρα",
    // Listing Detail
    listing_not_found: "Η αγγελια δεν βρεθηκε",
    report_submitted: "Αναφορα υποβληθηκε",
    report_submitted_desc: "Ευχαριστουμε για την αναφορα. Θα εξετασουμε την αγγελια.",
    report_listing: "Αναφορα αγγελιας",
    report_confirm: "Θελετε να αναφερετε αυτη την αγγελια;",
    contact_seller: "ΕΠΙΚΟΙΝΩΝΙΑ ΜΕ ΠΩΛΗΤΗ",
    back: "ΠΙΣΩ",
    seller_label: "ΠΩΛΗΤΗΣ",
    member_since: "Μελος απο",
    description: "ΠΕΡΙΓΡΑΦΗ",
    condition: "ΚΑΤΑΣΤΑΣΗ",
    pickup_only: "ΠΑΡΑΛΑΒΗ ΜΟΝΟ",
    views: "προβολες",
    // Stores
    stores_title: "ΚΑΤΑΣΤΗΜΑΤΑ",
    open_in_maps: "ΑΝΟΙΓΜΑ ΣΤΟ ΧΑΡΤΗ",
    store_hours: "ΩΡΑΡΙΟ",
    store_services: "ΥΠΗΡΕΣΙΕΣ",
    diagnostics: "ΔΙΑΓΝΩΣΤΙΚΑ",
    repairs: "ΕΠΙΣΚΕΥΕΣ",
    grading: "ΑΞΙΟΛΟΓΗΣΗ",
    sales: "ΠΩΛΗΣΕΙΣ",
    // Book Appointment
    book_appointment_title: "ΚΛΕΙΣΕ ΡΑΝΤΕΒΟΥ",
    select_date: "ΕΠΙΛΕΞΕ ΗΜΕΡΟΜΗΝΙΑ",
    select_time: "ΕΠΙΛΕΞΕ ΩΡΑ",
    morning: "ΠΡΩΙ",
    afternoon: "ΑΠΟΓΕΥΜΑ",
    diagnostic_info: "Διαγνωστικο τελος €10 (επιστρεφεται αν αγορασεις)",
    confirm_booking: "ΕΠΙΒΕΒΑΙΩΣΗ ΡΑΝΤΕΒΟΥ",
    booking_confirmed: "Το ραντεβου επιβεβαιωθηκε!",
    // Safety Tips
    safe_meetup: "ΑΣΦΑΛΗΣ ΣΥΝΑΝΤΗΣΗ",
    safety_tips_title: "ΣΥΜΒΟΥΛΕΣ ΑΣΦΑΛΕΙΑΣ",
    safety_tip_1: "Συναντησου παντα σε δημοσιο χωρο",
    safety_tip_2: "Χρησιμοποιησε τα καταστηματα iRepair για ασφαλεις συναντησεις",
    safety_tip_3: "Ελεγξε τη συσκευη πριν πληρωσεις",
    safety_tip_4: "Μην πληρωνεις ποτε εκ των προτερων",
    safety_tip_5: "Αν κατι φαινεται πολυ καλο για να ειναι αληθινο, πιθανοτατα δεν ειναι",
    // Auth
    email_placeholder: "Email",
    password_placeholder: "Κωδικος",
    forgot_password: "Ξεχασα τον κωδικο",
    create_account: "Δημιουργια λογαριασμου",
    login_title: "ΣΥΝΔΕΣΗ",
    register_title: "ΕΓΓΡΑΦΗ",
    or_continue_with: "η συνεχισε με",
    // Assistant
    assistant_title: "Βοηθος",
    assistant_subtitle: "Οδηγος αγορων",
    thinking: "Σκεφτομαι...",
    type_message: "Γραψε μηνυμα...",
    suggestions: "ΠΡΟΤΑΣΕΙΣ",
    hi_how_can_i_help: "Γεια! Πως μπορω να βοηθησω;",
    ask_about: "Ρωτα με για τιμες, συσκευες η ασφαλεια",
    open_assistant: "Ανοιξε τον βοηθο",
    close: "Κλεισιμο",
    send: "Αποστολη",
    // Tab Labels
    tab_home: "ΑΡΧΙΚΗ",
    tab_browse: "ΑΝΑΖΗΤΗΣΗ",
    tab_sell: "ΠΩΛΗΣΗ",
    tab_profile: "ΠΡΟΦΙΛ",
    // Home
    home_title: "MOBILE UNIT",
    home_subtitle: "Αγορασε και πουλησε συσκευες στη Ροδο",
    recent_listings: "ΠΡΟΣΦΑΤΕΣ ΑΓΓΕΛΙΕΣ",
    see_all: "ΔΕΣ ΟΛΑ",
    featured: "ΠΡΟΤΕΙΝΟΜΕΝΑ",
    verified: "ΠΙΣΤΟΠΟΙΗΜΕΝΟ",
    // Sell screen additional
    login_to_sell: "ΣΥΝΔΕΣΟΥ ΓΙΑ ΝΑ ΠΟΥΛΗΣΕΙΣ",
    login_to_sell_desc: "Δημιουργησε λογαριασμο για να καταχωρησεις τις συσκευες σου",
    submitted_for_approval: "ΥΠΟΒΛΗΘΗΚΕ ΓΙΑ ΕΓΚΡΙΣΗ",
    submitted_for_approval_desc: "Η αγγελια σου υποβληθηκε και θα εγκριθει συντομα",
    missing_fields: "ΛΕΙΠΟΥΝ ΣΤΟΙΧΕΙΑ",
    missing_fields_desc: "Συμπληρωσε ολα τα υποχρεωτικα πεδια",
    photos_required: "ΑΠΑΙΤΟΥΝΤΑΙ ΦΩΤΟΓΡΑΦΙΕΣ",
    photos_required_desc: "Προσθεσε τουλαχιστον 3 φωτογραφιες",
    select_brand: "Επιλεξε μαρκα",
    select_category_first: "Επιλεξε πρωτα κατηγορια",
    select_model: "Επιλεξε μοντελο",
    type_model: "Γραψε μοντελο",
    select_brand_first: "Επιλεξε πρωτα μαρκα",
    more_needed: "ΑΚΟΜΑ",
    other_brand: "ΑΛΛΟ",
    description_placeholder: "Περιγραψε τη συσκευη σου, συμπεριλαμβανομενων τυχον γρατζουνιων, αξεσουαρ, υγεια μπαταριας κ.λπ.",
    pricing_of_new: "της τιμης καινουργιου",
    // Category names for sell form
    category_phone: "ΚΙΝΗΤΟ",
    category_tablet: "TABLET",
    category_laptop: "LAPTOP",
    category_accessory: "ΑΞΕΣΟΥΑΡ",
    // Demo browse
    get_repair_quote: "Ζητα προσφορα επισκευης",
    ask_us: "Ρωτα μας",
    buy_sell_greece: "Αγορα & Πωληση συσκευων στην Ελλαδα",
    device_certification: "Πιστοποιηση & Διαγνωστικα συσκευων",
    categories: "ΚΑΤΗΓΟΡΙΕΣ",
    no_featured_yet: "Δεν υπαρχουν ακομα προτεινομενα",
    recent: "ΠΡΟΣΦΑΤΑ",
    all: "ΟΛΑ",
    no_listings_yet_demo: "Δεν υπαρχουν ακομα αγγελιες",
    // Book Appointment Screen additional
    appointment_booked: "ΡΑΝΤΕΒΟΥ ΚΛΕΙΣΤΗΚΕ!",
    appointment_booked_desc: "Θα λαβετε επιβεβαιωση συντομα",
    booking_error: "Δοκιμαστε ξανα η χρησιμοποιηστε το online booking",
    grading_at_irepair: "Βαθμολογηση στο iRepair",
    grading_at_irepair_desc: "Ελα να βαθμολογησουμε τη συσκευη σου στο iRepair Rhodes",
    diagnostic_fee_title: "€10 ΔΙΑΓΝΩΣΤΙΚΟ",
    diagnostic_fee_refund: "Επιστρεφεται αν αγορασετε",
    diagnostic_fee_info: "Το διαγνωστικο τελος καλυπτει τον ελεγχο της συσκευης και την εκδοση βαθμολογιας. Επιστρεφεται πληρως εαν πουλησετε τη συσκευη μεσω Mobile Unit.",
    booking: "ΚΡΑΤΗΣΗ...",
    book_appointment_cta: "ΚΛΕΙΣΕ ΡΑΝΤΕΒΟΥ",
    external_booking: "Η κλεισε online στο iRepair.gr",
  },
  en: {
    // Browse
    browse_title: "BROWSE",
    browse_subtitle: "Discover devices near you",
    search_placeholder: "Search...",
    all_categories: "ALL",
    phones: "PHONES",
    tablets: "TABLETS",
    laptops: "LAPTOPS",
    accessories: "ACCESSORIES",
    verified_only: "VERIFIED ONLY",
    no_listings: "NO LISTINGS FOUND",
    results_singular: "result",
    results_plural: "results",
    try_different_filters: "Try different filters or search",
    // Conditions
    condition_new: "NEW",
    condition_like_new: "LIKE NEW",
    condition_good: "GOOD",
    condition_fair: "FAIR",
    condition_parts: "FOR PARTS",
    // Condition descriptions
    condition_new_desc: "Unused, in original packaging",
    condition_like_new_desc: "Minimal use, excellent condition",
    condition_good_desc: "Minor signs of use",
    condition_fair_desc: "Visible use, fully functional",
    condition_parts_desc: "For parts only",
    // Sell
    sell_title: "NEW LISTING",
    sell_subtitle: "Sell your device on Mobile Unit",
    photos_label: "PHOTOS (3-10)",
    min_photos: "Minimum 3 photos required",
    title_label: "TITLE",
    category_label: "CATEGORY",
    condition_label: "CONDITION",
    city_label: "CITY",
    price_label: "PRICE",
    brand_label: "BRAND",
    model_label: "MODEL",
    location_label: "LOCATION",
    description_label: "DESCRIPTION",
    publish_button: "PUBLISH LISTING",
    creating: "CREATING...",
    pricing_guide: "PRICING GUIDE",
    vat_free: "VAT-free for used items",
    check_pricing: "Check Pandas Pricing",
    // Profile
    profile_title: "PROFILE",
    my_listings: "MY LISTINGS",
    listings_count: "LISTINGS",
    views_count: "VIEWS",
    create_new: "CREATE NEW LISTING",
    no_listings_yet: "You have no listings yet",
    create_first: "Create your first one",
    settings: "SETTINGS",
    support: "SUPPORT",
    legal: "LEGAL",
    sign_out: "SIGN OUT",
    sign_in: "SIGN IN",
    sign_in_to_profile: "Sign in to your profile",
    manage_listings_desc: "Manage your listings and account settings",
    user_fallback: "User",
    language_label: "LANGUAGE",
    // Service
    service_title: "SERVICES",
    grading_cta: "GET GRADED AT IREPAIR",
    book_appointment: "BOOK APPOINTMENT",
    diagnostic_fee: "DIAGNOSTIC FEE",
    refunded_on_purchase: "Refunded on purchase",
    // Common
    loading: "LOADING...",
    error: "ERROR",
    success: "SUCCESS",
    cancel: "CANCEL",
    confirm: "CONFIRM",
    rhodes: "RHODES",
    add: "ADD",
    remove: "REMOVE",
    // Onboarding
    welcome_title: "Welcome to Mobile Unit",
    welcome_subtitle: "Curated listings. Safe meetups. Local.",
    get_started: "Get Started",
    have_account: "I have an account",
    skip: "Skip",
    next: "Next",
    // Value props
    value_approved_title: "Approved Listings",
    value_approved_desc: "Every listing is reviewed by our team",
    value_pickup_title: "Safe Pickup",
    value_pickup_desc: "Meet at designated locations",
    value_inspection_title: "Inspection & Grading",
    value_inspection_desc: "Optional tech inspection",
    // City Gate
    select_city: "Select City",
    select_city_subtitle: "To see listings near you",
    available_now: "Available now",
    coming_soon: "Coming soon",
    other_city: "Other city / Abroad",
    use_location: "Use my location",
    // Waitlist
    join_waitlist: "Join the waitlist",
    waitlist_title: "Waitlist",
    waitlist_subtitle: "We'll notify you when we're available in your area",
    email_label: "EMAIL",
    interest_label: "INTEREST",
    buyer: "Buyer",
    seller: "Seller",
    both: "Both",
    phone_label: "PHONE (optional)",
    social_label: "INSTAGRAM/SOCIAL (optional)",
    notes_label: "NOTES (optional)",
    referral_code_label: "REFERRAL CODE (optional)",
    consent_label: "I agree to receive notifications",
    submit_waitlist: "Submit",
    // Waitlist Success
    waitlist_success_title: "You're on the list!",
    waitlist_success_subtitle: "We'll notify you when we launch in your area",
    your_referral_code: "Your referral code",
    share_referral: "Share to move up the list",
    share_button: "Share",
    copy_link: "Copy link",
    copied: "Copied!",
    view_demo: "View Demo",
    referral_bonus: "+3 positions per friend",
    // Demo Mode
    demo_banner: "Demo Mode",
    demo_locked_title: "Only available in Rhodes",
    demo_locked_subtitle: "Currently we're only available in Rhodes",
    demo_locked_cta: "Join the waitlist",
    // Cities
    city_rhodes: "Rhodes",
    city_athens: "Athens",
    city_thessaloniki: "Thessaloniki",
    city_patras: "Patras",
    city_heraklion: "Heraklion",
    city_larissa: "Larissa",
    city_volos: "Volos",
    city_ioannina: "Ioannina",
    city_chania: "Chania",
    city_london: "London",
    city_berlin: "Berlin",
    city_paris: "Paris",
    city_amsterdam: "Amsterdam",
    city_rome: "Rome",
    city_madrid: "Madrid",
    // Countries
    country_greece: "Greece",
    country_uk: "United Kingdom",
    country_germany: "Germany",
    country_france: "France",
    country_netherlands: "Netherlands",
    country_italy: "Italy",
    country_spain: "Spain",
    country_other: "Other country",
    // Listing Detail
    listing_not_found: "Listing not found",
    report_submitted: "Report submitted",
    report_submitted_desc: "Thank you for the report. We'll review this listing.",
    report_listing: "Report listing",
    report_confirm: "Do you want to report this listing?",
    contact_seller: "CONTACT SELLER",
    back: "BACK",
    seller_label: "SELLER",
    member_since: "Member since",
    description: "DESCRIPTION",
    condition: "CONDITION",
    pickup_only: "PICKUP ONLY",
    views: "views",
    // Stores
    stores_title: "STORES",
    open_in_maps: "OPEN IN MAPS",
    store_hours: "HOURS",
    store_services: "SERVICES",
    diagnostics: "DIAGNOSTICS",
    repairs: "REPAIRS",
    grading: "GRADING",
    sales: "SALES",
    // Book Appointment
    book_appointment_title: "BOOK APPOINTMENT",
    select_date: "SELECT DATE",
    select_time: "SELECT TIME",
    morning: "MORNING",
    afternoon: "AFTERNOON",
    diagnostic_info: "Diagnostic fee €10 (refunded on purchase)",
    confirm_booking: "CONFIRM BOOKING",
    booking_confirmed: "Booking confirmed!",
    // Safety Tips
    safe_meetup: "SAFE MEETUP",
    safety_tips_title: "SAFETY TIPS",
    safety_tip_1: "Always meet in a public place",
    safety_tip_2: "Use iRepair shops for safe meetups",
    safety_tip_3: "Inspect the device before paying",
    safety_tip_4: "Never pay upfront",
    safety_tip_5: "If it seems too good to be true, it probably is",
    // Auth
    email_placeholder: "Email",
    password_placeholder: "Password",
    forgot_password: "Forgot password",
    create_account: "Create account",
    login_title: "LOGIN",
    register_title: "REGISTER",
    or_continue_with: "or continue with",
    // Assistant
    assistant_title: "Assistant",
    assistant_subtitle: "Buyer's guide",
    thinking: "Thinking...",
    type_message: "Type a message...",
    suggestions: "SUGGESTIONS",
    hi_how_can_i_help: "Hi! How can I help you?",
    ask_about: "Ask me about pricing, devices, or safety",
    open_assistant: "Open assistant",
    close: "Close",
    send: "Send",
    // Tab Labels
    tab_home: "HOME",
    tab_browse: "BROWSE",
    tab_sell: "SELL",
    tab_profile: "PROFILE",
    // Home
    home_title: "MOBILE UNIT",
    home_subtitle: "Buy and sell devices in Rhodes",
    recent_listings: "RECENT LISTINGS",
    see_all: "SEE ALL",
    featured: "FEATURED",
    verified: "VERIFIED",
    // Sell screen additional
    login_to_sell: "SIGN IN TO SELL",
    login_to_sell_desc: "Create an account to list your devices",
    submitted_for_approval: "SUBMITTED FOR APPROVAL",
    submitted_for_approval_desc: "Your listing was submitted and will be approved soon",
    missing_fields: "MISSING FIELDS",
    missing_fields_desc: "Fill in all required fields",
    photos_required: "PHOTOS REQUIRED",
    photos_required_desc: "Add at least 3 photos",
    select_brand: "Select brand",
    select_category_first: "Select category first",
    select_model: "Select model",
    type_model: "Type model",
    select_brand_first: "Select brand first",
    more_needed: "MORE",
    other_brand: "OTHER",
    description_placeholder: "Describe your device, including any scratches, accessories, battery health, etc.",
    pricing_of_new: "of new price",
    // Category names for sell form
    category_phone: "PHONE",
    category_tablet: "TABLET",
    category_laptop: "LAPTOP",
    category_accessory: "ACCESSORY",
    // Demo browse
    get_repair_quote: "Get repair quote",
    ask_us: "Ask us",
    buy_sell_greece: "Buy & Sell devices in Greece",
    device_certification: "Device certification & diagnostics",
    categories: "CATEGORIES",
    no_featured_yet: "No featured listings yet",
    recent: "RECENT",
    all: "ALL",
    no_listings_yet_demo: "No listings yet",
    // Book Appointment Screen additional
    appointment_booked: "APPOINTMENT BOOKED!",
    appointment_booked_desc: "You'll receive confirmation shortly",
    booking_error: "Try again or use online booking",
    grading_at_irepair: "Grading at iRepair",
    grading_at_irepair_desc: "Get your device graded at iRepair Rhodes",
    diagnostic_fee_title: "€10 DIAGNOSTIC FEE",
    diagnostic_fee_refund: "Refunded on purchase",
    diagnostic_fee_info: "The diagnostic fee covers device inspection and grading. Fully refunded if you sell your device through Mobile Unit.",
    booking: "BOOKING...",
    book_appointment_cta: "BOOK APPOINTMENT",
    external_booking: "Or book online at iRepair.gr",
  },
} as const;

export type TranslationKey = keyof typeof translations.el;

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
}

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      language: "el",
      setLanguage: (lang) => set({ language: lang }),
      t: (key) => {
        const lang = get().language;
        return (translations[lang] as Record<TranslationKey, string>)[key] ?? key;
      },
    }),
    {
      name: "language-storage",
      storage: createJSONStorage(() => AsyncStorage),
    }
  )
);

// Helper hook for translations
export const useTranslation = () => {
  const language = useLanguageStore((s) => s.language);
  const setLanguage = useLanguageStore((s) => s.setLanguage);

  const t = (key: TranslationKey): string => {
    return (translations[language] as Record<TranslationKey, string>)[key] ?? key;
  };

  return { t, language, setLanguage };
};
